M48
; DRILL file {KiCad (6.0.4)} date Fri Oct  6 01:14:49 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-06T01:14:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X2.1673Y-2.3642
X2.1673Y-4.9232
X3.8406Y-2.3642
X3.8406Y-4.9232
T0
M30
