M48
; DRILL file {KiCad 9.0.0} date 2025-07-16T00:17:07+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-16T00:17:07+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X57.8Y-19.4
X57.8Y-37.4
T2
X31.55Y-19.8
X31.55Y-84.3
X186.8Y-19.8
X186.8Y-84.3
M30
